version: "3.9"

services:
    db-casa-embalagem:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "ictecnologia"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
volumes:
    postgres_data:
